name: build-and-test-arm-pr

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
  workflow_dispatch:

jobs:
  check-run-condition:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check-run-condition.outputs.run }}
    steps:
      - name: Check run condition
        id: check-run-condition
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Labeled now
            if [ "${{ github.event.label.name == 'ARM64' }}" = "true" ]; then
              RUN=true
            fi

            # Labeled before and synchronized
            if [ "${{ github.event.label.name }}" = "" ]; then
              if [ "${{ contains(github.event.pull_request.labels.*.name, 'ARM64') }}" = "true" ]; then
                RUN=true
              fi
            fi
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RUN=true
          fi

          if [ "$RUN" != "true" ]; then
            echo "Please add a proper label to run this workflow."
          fi

          echo ::set-output name=run::"$RUN"

  build-and-test-arm:
    needs: check-run-condition
    if: ${{ needs.check-run-condition.outputs.run == 'true' }}
    runs-on: [self-hosted, linux, ARM64]
    container: ros:galactic
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get modified packages
        id: get-modified-packages
        uses: autowarefoundation/autoware-github-actions/get-modified-packages@tier4/proposal

      - name: Build and test
        if: ${{ steps.get-modified-packages.outputs.modified-packages != '' }}
        uses: autowarefoundation/autoware-github-actions/colcon-build-and-test@tier4/proposal
        with:
          rosdistro: galactic
          target-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}
          build-depends-repos: build_depends.repos
