name: deploy-docs

on:
  push:
    branches:
      - main
      - tier4/proposal
    paths:
      - "mkdocs.yaml"
      - "**/*.md"
      - "**/*.svg"
      - "**/*.png"
      - "**/*.jpg"
  pull_request_target:
  workflow_dispatch:

jobs:
  check-run-condition:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check-run-condition.outputs.run }}
    steps:
      - name: Check run condition
        id: check-run-condition
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # Labeled now
            if [ "${{ github.event.label.name == 'documentation' }}" = "true" ]; then
              RUN=true
            fi

            # Labeled before and synchronized
            if [ "${{ github.event.label.name }}" = "" ]; then
              if [ "${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}" = "true" ]; then
                RUN=true
              fi
            fi
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RUN=true
          fi

          if [ "$RUN" != "true" ]; then
            echo "Please add a proper label to run this workflow."
          fi

          echo ::set-output name=run::"$RUN"

  deploy-docs:
    needs: check-run-condition
    if: ${{ needs.check-run-condition.outputs.run }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Deploy docs
        uses: autowarefoundation/autoware-github-actions/deploy-docs@tier4/proposal
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
