name: sync-awf-latest

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:
  repository_dispatch:
    types: [sync-awf-latest]

jobs:
  sync-awf-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Commit Results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          echo "PO"
