name: sync-awf-latest

on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch:

jobs:
  sync-awf-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git remote add awf git@github.com:autowarefoundation/autoware_launch
          git fetch awf
          git checkout awf/main
          git checkout -b awf-latest
          git push origin awf-latest -f
